server:
  port: 8084
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.path: /h2-console
    settings.trace: false
    settings.web-allow-others: false
    console.enabled: true

management:
  endpoints:
    web.base-path: /main/actuator

